### ISSUE TITLE
ReferenceError: MSFlowConnection is not defined

### ISSUE THREAD

**Issue by silenceleewq** [sketch-hq/SketchAPI#817]
I drag the Javascript files from Sketch/Contents/Resources/*.
the idea show me a exception that I paste blow.
so...what is MSFlowConnection?
`
ReferenceError: MSFlowConnection is not defined
    at Object.<anonymous> (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:33435)
    at t (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:115)
    at Object.<anonymous> (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:29147)
    at t (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:115)
    at Object.<anonymous> (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:8925)
    at t (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:115)
    at Object.<anonymous> (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:12203)
    at t (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:115)
    at Object.<anonymous> (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:26709)
    at t (/Users/IdeaProjects/SketchAPI/Sketch/SketchAPI.js:1:115)
`

**Comment by christianklotz** [comment]
`MSFlowConnection` is an internal class, only available within the Sketch plugin runtime environment. The API requires Sketch to work.
