### ISSUE TITLE
No structure encoding found for CGRect

### ISSUE THREAD

**Issue by mianaliasjad** [sketch-hq/SketchAPI#909]
i am trying the example code in the run script window. but this error happends.

`Error: An Obj-C exception occurred.
    at [native code] (/)
    at value (/Applications/Sketch.app/Contents/Resources/SketchAPI.js:1:13803)
    at r (/Applications/Sketch.app/Contents/Resources/SketchAPI.js:1:29224)
    at onRun (/Users/aliasjad/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:12:22)
  nativeException: No structure encoding found for CGRect
Script executed in 0.039289s`

**Comment by rodionovd** [comment]
Please share the exact code snippet you're trying to run.

**Comment by SteveEdson** [comment]
Getting the same issue here: https://github.com/skpm/sketch-module-web-view/issues/183

Seems pretty common. Works with Sketch 93 onwards, but nothing before then.
